title = "Diana Tuck"
baseURL = "https://dianatuck.com"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/gopher_java.png"
  description = ""
  facebook = "https://www.facebook.com/diana.tuck9"
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/dtuck9"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/dianatuck/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/sintra.jpg"
  recent_posts_number = 2
